### ISSUE TITLE
Добавить поддержку для PhpStorm 2022.3.1

### ISSUE THREAD

**Issue by sergey-yabloncev** [VKCOM/noverify-phpstorm#2]
Not compatible with the version of your running IDE (PhpStorm 2022.3.1)

**Comment by alnidok** [comment]
@Danil42Russia
Do you plan to support the plugin for new PhpStorm versions (2022.3+)?
https://plugins.jetbrains.com/plugin/19465-noverify-support/versions

There is only one reason that prevents us to use noverify in our team (PhpStorm 2023+).

**Comment by Hidanio** [comment]
@alnidok Hello! Sorry for the too long answer. Yes, we will add it very soon!

**Comment by Hidanio** [comment]
@alnidok @sergey-yabloncev
Done.
